# Generated by Django 5.2.14 on 2026-06-01 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('tech_stacks', models.JSONField(blank=True, default=list)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('resume_id', models.CharField(blank=True, default='', max_length=100)),
                ('resume_hash', models.CharField(blank=True, default='', max_length=128)),
                ('parse_status', models.CharField(blank=True, default='', max_length=30)),
                ('parsed_resume_json', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidates_profile',
            },
        ),
    ]
