# Generated by Django 4.2.13 on 2026-08-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='ai_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='job_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='location',
            field=models.CharField(blank=True, default='Bangalore, India', max_length=255),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='notification_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='resume_visibility',
            field=models.CharField(default='recruiter_only', max_length=30),
        ),
    ]
