# Generated by Django 5.2.14 on 2026-06-01 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('hr_pending', 'HR Pending'), ('hr_passed', 'HR Passed'), ('hr_failed', 'HR Failed'), ('tech_pending', 'Tech Pending'), ('tech_passed', 'Tech Passed'), ('tech_failed', 'Tech Failed'), ('offer_sent', 'Offer Sent'), ('offer_signed', 'Offer Signed'), ('offer_accepted', 'Offer Accepted'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='applied', max_length=30)),
                ('match_score', models.IntegerField(blank=True, null=True)),
                ('hr_score', models.FloatField(blank=True, null=True)),
                ('tech_score', models.FloatField(blank=True, null=True)),
                ('tech_language', models.CharField(blank=True, default='', max_length=50)),
                ('next_action', models.CharField(blank=True, default='', max_length=50)),
                ('last_failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('retry_eligible_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'db_table': 'applications_application',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('HR', 'HR'), ('TECH', 'Tech')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('submitted', 'Submitted')], default='active', max_length=20)),
                ('language', models.CharField(blank=True, default='', max_length=50)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('duration_secs', models.IntegerField(default=1800)),
                ('total_questions', models.IntegerField(default=10)),
                ('answered_questions', models.IntegerField(default=0)),
                ('exam_mode', models.CharField(default='mcq', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='applications.application')),
            ],
            options={
                'db_table': 'applications_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('correct_option', models.IntegerField(default=0)),
                ('explanation', models.TextField(blank=True, default='')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='applications.assessmentsession')),
            ],
            options={
                'db_table': 'applications_question',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('offer_pdf_url', models.CharField(blank=True, default='', max_length=500)),
                ('signed_pdf_url', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='applications.application')),
            ],
            options={
                'db_table': 'applications_offer',
            },
        ),
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option_index', models.IntegerField()),
                ('is_correct', models.BooleanField(default=False)),
                ('time_spent_ms', models.BigIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='applications.assessmentquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='applications.assessmentsession')),
            ],
            options={
                'db_table': 'applications_answer',
                'unique_together': {('session', 'question')},
            },
        ),
    ]
